env:
  node: true
  es2021: true
  # commonjs: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
globals:
  AppConfigs: true
  Logger: true
  __stubs: true
